version: '2.1'

services:
  nginx:
    image: bitnami/nginx:latest
    container_name: tribe-nginx
    depends_on:
      - php
    networks:
      - app-tier
    ports:
      - 8080:8080
    volumes:
      - ./docker/nginx/tribe.conf:/opt/bitnami/nginx/conf/vhosts/tribe.conf
      - .:/app

  php:
    build: docker/php
    container_name: tribe-php
    depends_on:
       - mysql
    networks:
      - app-tier
    volumes:
      - .:/app

  mysql:
    image: bitnami/mysql:latest
    container_name: tribe-mysql
    networks:
      - app-tier
    ports:
      - 3308:3306
    volumes:
      - ./dump:/var/www/dump
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - MYSQL_DATABASE=tribe
      - MYSQL_USER=tribe
      - MYSQL_PASSWORD=tribe
      - MYSQL_ROOT_PASSWORD=rootPassword
      - MYSQL_PORT=3306

networks:
  app-tier:
    driver: bridge
